version: '3.7'
services:
  mysql:
    image: mysql/mysql-server:5.7.37
    restart: always
    env_file:
      - .env
    ports:
      - 3306:3306
      - 33060:33060
    volumes:
      - ./src/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

  legacy-php:
    depends_on:
      - mysql
    image: orsolin/docker-php-5.3-apache
    env_file:
      - .env
    volumes:
      - ./src:/var/www/html
    ports:
      - "5000:80"

volumes:
  mysql_data:
